# Generated by Django 3.0 on 2019-12-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auto_20191212_2033'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='latitude between -90 and 90',
        ),
        migrations.RemoveConstraint(
            model_name='location',
            name='longitude between -180 and 180',
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(check=models.Q(latitude__range=(-90, 90)), name='latitude between -90 and 90'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(check=models.Q(longitude__range=(-180, 180)), name='longitude between -180 and 180'),
        ),
    ]
