# Generated by Django 2.1.7 on 2019-04-09 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityName', models.CharField(blank=True, max_length=500)),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('sunday', models.BooleanField()),
                ('advanceNotice', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.Location')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('recipient', 'location')},
        ),
    ]
