# Generated by Django 2.1.7 on 2019-04-09 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20190409_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weatherOption', models.CharField(choices=[('apparentTemperature', 'Apparent Temperature'), ('apparentTemperatureHigh', 'Apparent Temperature High'), ('apparentTemperatureHighTime', 'Apparent Temperature High Time'), ('apparentTemperatureLow', 'Apparent Temperature Low'), ('apparentTemperatureLowTime', 'Apparent Temperature Low Time'), ('cloudCover', 'Cloud Cover'), ('dewPoint', 'Dew Point'), ('humidity', 'Humidity'), ('icon', 'Icon'), ('moonPhase', 'Moon Phase'), ('nearestStormBearing', 'Nearest Storm Bearing'), ('nearestStormDistance', 'Nearest Storm Distance'), ('ozone', 'Ozone'), ('precipAccumulation', 'Precipitation Accumulation'), ('precipIntensity', 'Precipitation Intesity'), ('precipIntensityError', 'Precipitation Intensity Error'), ('precipIntensityMax', 'Maximum Precipitation Intensity'), ('precipIntensityMaxTime', 'Precipitation Intensity Max Time'), ('precipProbability', 'Precipitation Probability'), ('precipType', 'Precipitation Type'), ('pressure', 'Pressure'), ('summary', 'Summary'), ('sunriseTime', 'Sunrise Time'), ('sunsetTime', 'Sunset Time'), ('temperature', 'Temperature'), ('temperatureHigh', 'Temperature High'), ('temperatureHighTime', 'Temperature High Time'), ('temperatureLow', 'Temperature Low'), ('temperatureLowTime', 'Temperature Low Time'), ('time', 'Time'), ('uvIndex', 'UV Index'), ('uvIndexTime', 'UV Index Time'), ('visibility', 'Visibility'), ('windBearing', 'Wind Bearing'), ('windGust', 'Wind Gust'), ('windGustTime', 'Wind Gust Time'), ('windSpeed', 'Wind Speed')], max_length=500)),
                ('stringData', models.TextField(blank=True)),
                ('numData', models.DecimalField(decimal_places=4, max_digits=8)),
                ('compareOption', models.CharField(choices=[('exactly', 'exactly'), ('between', 'between'), ('more', 'more than'), ('less', 'less than')], max_length=7)),
                ('range', models.DecimalField(decimal_places=4, max_digits=8)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.Location')),
            ],
        ),
    ]
