# Generated by Django 3.0 on 2019-12-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20191213_0458'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='filter',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(_negated=True, compare_option__iexact='between'), ('range__isnull', True)), models.Q(('compare_option__iexact', 'between'), ('range__isnull', False)), _connector='OR'), name='if compare option between range is not null'),
        ),
    ]
