# Generated by Django 3.0 on 2019-12-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_auto_20191213_0641'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='filter',
            name='if compare option between range is not null',
        ),
        migrations.AddConstraint(
            model_name='filter',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(_negated=True, compare_option__iexact='between'), ('range__isnull', True)), models.Q(('compare_option__iexact', 'between'), ('range__isnull', False)), _connector='OR'), name='if compare option is between, range is not null'),
        ),
    ]
